spring.application.name=patiomaru-parking-backend
server.port=8081

logging.level.root=INFO
logging.level.co.edu.uco.patiomaruparking=DEBUG
logging.level.co.edu.uco.patiomaruparking.controlador=TRACE
logging.level.co.edu.uco.patiomaruparking.negocio=DEBUG
logging.level.co.edu.uco.patiomaruparking.datos=DEBUG
logging.level.org.springframework=INFO
logging.level.org.apache.catalina=WARN

spring.datasource.url=jdbc:postgresql://localhost:5432/patiomaru_db?currentSchema=restaurante_yeison
spring.datasource.username=postgres
spring.datasource.password=Ajstyles4#
spring.datasource.driver-class-name=org.postgresql.Driver