spring.application.name=patiomaru-parking-backend
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/patiomaru_db?currentSchema=restaurante_yeison
spring.datasource.username=postgres
spring.datasource.password=Ajstyles4#
spring.datasource.driver-class-name=org.postgresql.Driver